# This is the configuration file for Ghostty.
#
# Run `ghostty +show-config --default --docs` to view a list of
# all available config options and their default values.
#
# Additionally, each config option is also explained in detail
# on Ghostty's website, at https://ghostty.org/docs/config.

adjust-cell-height = 2
clipboard-trim-trailing-spaces = true
confirm-close-surface          = false
copy-on-select                 = false
cursor-invert-fg-bg            = true
font-family                    = 'FiraCode Nerd Font Mono'
font-size                      = 12
font-thicken                   = 1
macos-option-as-alt            = left
macos-icon                     = retro
#macos-titlebar-style           = hidden
#macos-window-buttons           = hidden
minimum-contrast               = 1.25
mouse-hide-while-typing        = true
window-height                  = 65
window-width                   = 180
window-padding-x               = 3
window-padding-y               = 5,0

# Keybindings
keybind = cmd+alt+arrow_left=text:\x07\x70
keybind = cmd+alt+arrow_right=text:\x07\x6E
keybind = ctrl+shift+arrow_left=text:\x07\x1B\x5B\x43
keybind = ctrl+shift+arrow_right=text:\x07\x1B\x5B\x44
keybind = ctrl+shift+arrow_down=text:\x07\x1B\x5B\x42
keybind = ctrl+shift+arrow_up=text:\x07\x1B\x5B\x41
keybind = shift+enter=text:\x1b\r

# Colorscheme
# The dark variant of melange
background = #292522
foreground = #ECE1D7
palette = 0=#867462
palette = 1=#D47766
palette = 2=#85B695
palette = 3=#EBC06D
palette = 4=#A3A9CE
palette = 5=#CF9BC2
palette = 6=#89B3B6
palette = 7=#ECE1D7
palette = 8=#34302C
palette = 9=#BD8183
palette = 10=#78997A
palette = 11=#E49B5D
palette = 12=#7F91B2
palette = 13=#B380B0
palette = 14=#7B9695
palette = 15=#C1A78E
selection-background = #403a36
selection-foreground = #c1a78e
